Repository RaboDeToro-hub-2/uvlhub, pull requests merged in 2024-11, with the labels that each got.

#20 Configuration: automatize deploys
  .github/workflows/deloyment_on_render_production.yml
  .github/workflows/deloyment_on_render_staging.yml
  .github/workflows/deloyment_on_webhook.yml
  .github/workflows/deployment_on_dockerhub.yml
  .github/workflows/deployment_on_render_development.yml
Labels: configuration

#19 fix: add additional types to conventional commits
  .github/workflows/commits.yml
Labels: configuration

#25 ci: update checkout step to use pull request base reference
  .github/workflows/deployment_on_render_development.yml
Labels: bug, configuration

#24 Feature/login with GitHub
  app/modules/auth/.env.example
  app/modules/auth/models.py
  app/modules/auth/routes.py
  app/modules/auth/services.py
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/signup_form.html
  app/static/css/own.css
  app/static/img/logos/github-mark.svg
  requirements.txt
Labels: feature

#26 Feature/sign up with email confirmation
  app/__init__.py
  app/modules/auth/models.py
  app/modules/auth/repositories.py
  app/modules/auth/routes.py
  app/modules/auth/services.py
  app/modules/auth/tests/test_unit.py
  app/modules/mail/.env.example
  app/modules/mail/__init__.py
  app/modules/mail/forms.py
  app/modules/mail/models.py
  app/modules/mail/repositories.py
  app/modules/mail/routes.py
  app/modules/mail/seeders.py
  app/modules/mail/services.py
  app/modules/mail/templates/mail/index.html
  app/modules/mail/tests/__init__.py
  app/modules/mail/tests/locustfile.py
  app/modules/mail/tests/test_selenium.py
  app/modules/mail/tests/test_unit.py
  migrations/versions/86d9288d7145_.py
  requirements.txt
Labels: feature

#36 Configuration/bring workflows to develop
  .github/workflows/commits.yml
  .github/workflows/deloyment_on_render_production.yml
  .github/workflows/deloyment_on_render_staging.yml
  .github/workflows/deloyment_on_webhook.yml
  .github/workflows/deployment_on_dockerhub.yml
  .github/workflows/deployment_on_render_development.yml
Labels: configuration
